config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :visit_requests
  resources :visits
  devise_for :users
  resources :home
  resources :admin
  resources :tour
  resources :contact
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:scheduled, :user_id, :visitor_name, :visitor_email, :visit_type)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_with(model: visit, local: true) do |form| %>
  <% if visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :scheduled %>
    <%= form.datetime_select :scheduled, id: :visit_scheduled %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :visit_user_id %>
  </div>

  <div class="field">
    <%= form.label :visitor_name %>
    <%= form.text_field :visitor_name, id: :visit_visitor_name %>
  </div>

  <div class="field">
    <%= form.label :visitor_email %>
    <%= form.text_field :visitor_email, id: :visit_visitor_email %>
  </div>

  <div class="field">
    <%= form.label :visit_type %>
    <%= form.number_field :visit_type, id: :visit_visit_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>

    <h1>Próximas visitas</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Horario</th>
          <th>Guía</th>
          <th>Nombre de Organizador</th>
          <th>Email de Organizador</th>
          <th>Tipo de Visita</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @visits.each do |visit| %>
        <tr>
          <td><%= visit.scheduled %></td>
          <td><%= visit.user %></td>
          <td><%= visit.visitor_name %></td>
          <td><%= visit.visitor_email %></td>
          <td><%= visit.visit_type %></td>
          <td><%= link_to 'Show', visit %></td>
          <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
          <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Visit', new_visit_path %>
  </div>
</div>

app/views/visits/new.html.erb
<div class="row">
  <div class="col-md-12">

    <h1>New Visit</h1>

    <%= render 'form', visit: @visit %>

    <%= link_to 'Back', visits_path %>

  </div>
</div>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scheduled:</strong>
  <%= @visit.scheduled %>
</p>

<p>
  <strong>User:</strong>
  <%= @visit.user %>
</p>

<p>
  <strong>Visitor name:</strong>
  <%= @visit.visitor_name %>
</p>

<p>
  <strong>Visitor email:</strong>
  <%= @visit.visitor_email %>
</p>

<p>
  <strong>Visit type:</strong>
  <%= @visit.visit_type %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>