config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :visit_requests
  resources :visits
  devise_for :users
  resources :home
  resources :admin
  resources :tour
  resources :contact
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
end

app/models/visit_request.rb
class VisitRequest < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def index
    @requests = VisitRequest.where(approved: false).order(created_at: :desc)
    @recorridos = Visit.where('scheduled >= ?', DateTime.now.beginning_of_day).order(scheduled: :desc)
    @users = User.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :embedded_video)
    end
end

app/controllers/tour_controller.rb
class TourController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # NOTE: Using `strong_parameters` gem
      params.require(:user).permit(:name, :access, :last_name, :phone_number, :password, :email)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:scheduled, :user_id, :visitor_name, :visitor_email, :visit_type)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tour_helper.rb
module TourHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visit_requests_helper.rb
module VisitRequestsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/admin/index.html.erb
<section class="info">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Solicitudes de visitas:</h2>
        <table class="table">
          <thead>
            <tr>
              <th>Solicitante</th>
              <th>Email</th>
              <th>Tipo de visita</th>
              <th>Fecha</th>
              <th colspan="2" width="20%"></th>
            </tr>
          </thead>
          <tbody>
            <% @requests.each do |req| %>
            <tr>
              <td><%= req.visitor_name %></td>
              <td><%= req.visitor_email %></td>
              <td><%= req.visit_type == 0 ? "CCU" : "Date un Rol" %></td>
              <td><%= req.scheduled.strftime('%Y-%m-%d') %></td>
              <td><button class="btn btn-success">Aprobar</button></td>
              <td><button class="btn btn-danger">Declinar</button></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-12">
        <h2>Próximos Recorridos:</h2>
        <table class="table">
          <thead>
            <tr>
              <th>Guía</th>
              <th>Solicitante</th>
              <th>Email</th>
              <th>Tipo de visita</th>
              <th>Fecha</th>
            </tr>
          </thead>
          <tbody>
            <% @recorridos.each do |rec| %>
            <tr>
              <td><%= User.find(rec.user_id).name %></td>
              <td><%= rec.visitor_name %></td>
              <td><%= rec.visitor_email %></td>
              <td><%= rec.visit_type == 0 ? "CCU" : "Date un Rol" %></td>
              <td><%= rec.scheduled.strftime('%Y-%m-%d') %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-12">
        <h2>Guías:</h2>
        <table class="table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Email</th>
              <th>Fecha de ingreso</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.created_at.strftime('%Y-%m-%d') %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Visitas Guiadas CCU</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="/"><img src="/escudo_unam.svg" class="img-responsive" style="max-height:70px" alt=""></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Inicio', root_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recorridos <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'CCU', root_path(anchor: 'visita-ccu') %></li>
                  <li><%= link_to 'Date un Rol', root_path(anchor: 'date-un-rol') %></li>
                </ul>
              </li>
              <li><%= link_to 'Agenda tu visita', new_visit_request_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contacto <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Directorio', contact_index_path %></li>
                  <li><%= link_to 'Servicio Social', contact_index_path %></li>
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div>
      </nav>
    </header>
      <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <p>
            <b>Visitas Guiadas</b>
<br><br>
Visitas a grupos escolares, público en general, niños, adultos mayores y personas con capacidades diferentes.
<br>
Informes: 5622 7008 o visitas@unam.mx
<br>
Facebook: <a href="https://facebook.com/visitasguiadas.ccuunam">Visitas Guiadas CCU UNAM</a>
      <br>
Twitter:  <a href="https://twitter.com/CulturaUNAM">@CulturaUNAM</a>
</p>
          </div>
          <div class="col-md-4">
            <img src="/cultura_unam.png" class="img-responsive pull-right" style="max-height:100px" alt="">
          </div>
        </div>
      </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js" charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.es.min.js" charset="utf-8"></script>
    <script type="text/javascript">
      $('.datepicker').datepicker({
        format: 'dd/mm/yyyy',
        language: 'es',
        startDate: '+1d'
      });
    </script>
  </body>
</html>